# Generated by Django 4.0.4 on 2022-04-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
